jenkins:
  image: "jenkins-docker:v1.0"
  container_name: "jenkins-docker"
  ports:
      - "172.10.11.211:1082:8080"
      - "172.10.11.211:50002:50000"
  volumes:
      - /etc/localtime:/etc/localtime
      - ./jenkins_home/:/var/jenkins_home/
      - ./jenkins_backup/:/var/jenkins_backup/
      - /opt/yocto/.ssh/:/var/jenkins_home/.ssh/
      - /opt/yocto-rel/yocto/:/opt/yocto-rel/yocto/
